name: Vscode Publish

on:
  push:
    branches:
      - master
    tags:
      - v*

permissions: {}

jobs:
  publish-vscode:
    permissions:
      contents: write
    if: "contains(github.event.head_commit.message, 'release')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm i --frozen-lockfile --ignore-scripts

      - uses: lannonbr/vsce-action@3.0.0
        with:
          args: publish -p $VSCE_TOKEN
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Create Release for Tag
        id: release_tag
        uses: yyx990803/release-tag@master
        env:
          GITHUB_TOKEN: ${{ secrets.GHB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          body: |
            Please refer to [CHANGELOG.md](https://github.com/hemengke1997/vscode-image-manager/blob/master/CHANGELOG.md) for details.
